### ISSUE TITLE
Referene

### ISSUE THREAD

**Issue by trungtpham** [espdev/csaps#1]
Hi, Thanks for the good work. Do you have a reference of your formulation? eg mathematical solution for cubic smoothing spline that you used to implement.

Thanks,
Trung

**Comment by espdev** [comment]
Hi @trungtpham, 
You can find the mathematical formulation for cubic smoothing spline in the book [Carl de Boor, A Practical Guide to Splines](https://www.springer.com/us/book/9780387953663)

Well, I guess I could add this reference to readme.
Thanks!

**Comment by espdev** [comment]
Done

**Comment by trungtpham** [comment]
Thanks @espdev
