### ISSUE TITLE
Automatic Smoothing Result

### ISSUE THREAD

**Issue by ArthurBook** [espdev/csaps#19]
Hi!
Thanks for a great package.
Is there any source for how the smoothing parameter "smooth" is determined automatically?
I can not understand where in the code that it is written? 
Could you help me by providing the source for the algorithm that is used, or maybe describe here the logic behind it or where in the code that I can find it?

This could be very useful to add to the docs as well?

Thanks a lot in advance.

**Comment by espdev** [comment]
Hi Arthur,

In the project the method from MATLAB csaps function is used (it is not the original method from the book and PGS).

See the code:
https://github.com/espdev/csaps/blob/a05249b733c426b72c5ee669cd33cbff7682b01a/csaps/_sspumv.py#L211-L222

https://github.com/espdev/csaps/blob/a05249b733c426b72c5ee669cd33cbff7682b01a/csaps/_sspumv.py#L248-L261

In other words, I will quote MATLAB documentation:

> The favorable range for `p` is often near `1/(1 + h3/6)`, where `h` is the average spacing of the data sites. The function chooses a default value for `p` within this range.

[link](https://www.mathworks.com/help/curvefit/csaps.html (see "P - Smoothing parameter" section)

**Comment by ArthurBook** [comment]
Thank you very much for your help!
