### ISSUE TITLE
results of UnivariateCubicSmoothingSpline for smooth = 0

### ISSUE THREAD

**Issue by jadeiX** [espdev/csaps#2]
@espdev Thank you for writing this library. it is awesome and very useful. I noticed that when I use UnivariateCubicSmoothingSpline with smooth = 0,  I don't get a straight line, instead, it does "auto smooth".

using the example you gave with smooth = 0 I get:
![image](https://user-images.githubusercontent.com/32917209/58765859-1e01cb00-852c-11e9-914d-ef9cb454ebfe.png)

what I expected to get is the following:
![image](https://user-images.githubusercontent.com/32917209/58765836-e3982e00-852b-11e9-9f22-7e2c0ea624ca.png)

I believe the root cause for this is that the following if statement in the code would be false for  self._smooth = 0:
`if self._smooth:`
`                p = self._smooth`
` else:`
`                 p = self._compute_smooth(r, qtwq)`

proposed correction:
`if (self._smooth or self._smooth==0):`
`                p = self._smooth`
` else:`
`                 p = self._compute_smooth(r, qtwq)`

**Comment by espdev** [comment]
@jadeiX thanks for the report! This bug has been fixed in [v0.4.2.
](https://pypi.org/project/csaps/0.4.2/).
