### ISSUE TITLE
Duplicate x values will cause an error

### ISSUE THREAD

**Issue by randomizedthinking** [espdev/csaps#39]
The current implementation cannot handle duplicated x values. In practice, it is common that we observe multiple y-values at the same x value.

**Comment by espdev** [comment]
Hello,

X-values **must** strictly monotonically increase or decrease. In other cases we cannot solve the equations to compute the spline.

You need to remove duplicate values from your dataset. You can use [numpy.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) funtion for example.

**Comment by espdev** [comment]
If you have multiple y-values at the same x value you need to use parametrization:
`x = f(t); y = f(t)` where `t` is strictly monotonically increase or decrease.
