### ISSUE TITLE
How to cite

### ISSUE THREAD

**Issue by welschma** [espdev/csaps#40]
Hey, 
I'm using your csaps package in a academic context and would like to add a reference to it. Do you have a preferred way on how you would like to be cited, e.g. a bibtex entry or something?

Cheers

**Comment by espdev** [comment]
Hi @welschma,

You could use the way you like to cite the package.

I like the idea to use BibLaTeX entry. For example:

```
@software{csaps,
  author = {{Eugene Prilepin}},
  title = {CSAPS - Cubic Spline Approximation (Smoothing)},
  url = {https://github.com/espdev/csaps},
  version = {1.0.3},
  date = {2021-01-01},
}
```

**Comment by welschma** [comment]
Thanks for faste reply :)
