### ISSUE TITLE
Release a version supprting >= scipi 1.7

### ISSUE THREAD

**Issue by alecf** [espdev/csaps#53]
@espdev - I noticed that the 1.0.4 release doesn't allow scipy 1.7, but it looks like there has been a PR merged into `master` (#50) that supports it. Any chance of a 1.0.5 release to PyPI?

**Comment by espdev** [comment]
Hi @alecf, 
I'm planning to make a new release next week.

**Comment by hashb** [comment]
Any update on the new release?

**Comment by espdev** [comment]
Done
https://pypi.org/project/csaps/1.1.0/
