### ISSUE TITLE
CSAPS on conda-forge

### ISSUE THREAD

**Issue by aafkevandenberg** [espdev/csaps#57]
Dear developers,

CSAPS works great, but providing CSAPS only through pypi currently makes it impossible to implement it as a dependency on conda packages (see https://github.com/conda/conda-build/issues/548).

Could you please publish CSAPS on conda-forge? 
Many people use conda for package installation/management. 

Creating a conda-forge recipe for a PyPI package like CSAPS can be done using the instructions on the [conda-forge site](https://conda-forge.org/#add_recipe). 

Cheers,

**Comment by espdev** [comment]
Hi @aafkevandenberg,

I don't use conda and conda package manager. If you are familiar with conda ecosystem you can do a PR to add csaps package to conda-forge. Also someone has to support the package in conda-forge and update the package version from time to time. I'm sorry, but I have no time and motivation to do that.

**Comment by aafkevandenberg** [comment]
Hi @espdev,

I understand that this is not your priority, thank you for answering!

Best regards,
