### ISSUE TITLE
Issue with the smooth parameter.

### ISSUE THREAD

**Issue by lucassherbrook** [espdev/csaps#66]
What the csaps function looks like without smooth parameter:

```from csaps import csaps
spline = csaps(x_points, y_points)
plt.plot(x, fit)
plt.scatter(x_points, y_points)
plt.show()
```
![spline_plot_no_smoothing](https://github.com/espdev/csaps/assets/62917015/175c5162-e24a-449e-8b6d-f31f636450fd)

What the csaps function looks like with any non-default smoothing parameter, even if small:

```from csaps import csaps
spline = csaps(x_points, y_points, smooth=.05)
plt.plot(x, fit)
plt.scatter(x_points, y_points)
plt.show()
```
![spline_plot_with_smoothing](https://github.com/espdev/csaps/assets/62917015/16b0d329-7aad-4fd7-ba92-f1ead379c9d9)

**Comment by espdev** [comment]
Hello @lucassherbrook,

Could you give a sample of your real data for checking?

**Comment by lucassherbrook** [comment]
Here is the data I inputted to csaps:
[spline_data.csv](https://github.com/espdev/csaps/files/11730799/spline_data.csv)

It outputs linear regression for me when using any smoothing parameter (including for those outside of the [0,1] range).

**Comment by espdev** [comment]
The X-data scaling on which the spline is make is such that the value of the smoothing parameter is in a very narrow range, close to 1.

The is the value of `smooth` that is automatically calculated: `0.999999999727055`
You can change the value to `0.999998` and you will see that the spline fits your data correctly.
![2023-06-13_19-47-56](https://github.com/espdev/csaps/assets/1299189/bba4ab0b-9ab7-474a-be07-ac2d143d36c0)


Nevertheless, this is not very convenient. You can try to use [smooth normalization](https://csaps.readthedocs.io/en/latest/tutorial.html#smooth-normalization) to avoid the problems with X-data scaling.

```python
yi = csaps(x, y, xi, smooth=0.5, normalizedsmooth=True)
```

![2023-06-13_19-51-52](https://github.com/espdev/csaps/assets/1299189/81da0827-e48d-430d-98fd-6ef7ce0ec46f)

In this case the effect from the smooth parameter will be almost linear in the range from 0 to 1.
