### ISSUE TITLE
Interpolate on irregular grid

### ISSUE THREAD

**Issue by sroener** [espdev/csaps#69]
Hi, 

as far as I understand, CSAPS is able to work with univariate, multivariate (both depending x being 1dimensional) and ND-gridded data. 

In my use case, I have an irregular grid with missing values in random positions. Is it possible to use CSAPS on that kind of data? 

As an example, would CSAPS work on data generated like in the [scipy.griddata example](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html)?

If irregular grids don't work, would it be feasible to use NaNs to fill the grid?

**Comment by espdev** [comment]
Currently csaps cannot work with NaN values. If the input data contains NaN values, then all values will be NaN in the output data. csaps only can extrapolate values outside the regular grid not fill NaN values inside the grid.

You can use `nearest` interpolation method in `griddata` function to produce the data without NaN, or use `fill_value` to fill NaN values in the interpolated data. I understand using `fill_value` is not very flexible and may not be applicable in some cases.

**Comment by sroener** [comment]
Ok, thanks for your explanation. 

I still have a hard time understanding how the weights work and why it is not possible to attach weights to individual data points. 

You mention in #24 that for the ND gridded interpolation, the algorithm performs univariate smoothing using the weight vector. In the [tutorial](https://csaps.readthedocs.io/en/latest/tutorial.html), you show an example of weighting a univariate interpolation using weights for individual points.

Wouldn't it be possible to provide the weights as ND-array of the same shape as y and query the correspondig weight vectors similar to the Y and perform the respective univariate splines? Everything downstream of that should still be working as before.

**Comment by espdev** [comment]
In my [comment](https://github.com/espdev/csaps/issues/24#issuecomment-644961451) I provide a code fragment showing the use of weight vectors in ND-grid smoothing. We cannot use weight surface because we apply weights to univariate splines by each dimension.

You can try to change the algorithm for ND-grid case to make possible to use weight surface instead of weight vectors. PRs are always welcome. :)

**Comment by espdev** [comment]
> Do you have a preferred way of reaching out if questions regarding the code arise?

You can just ask here in this issue.
